server:
  port: 8085
spring:
  application:
    name: DRUGS-SERVICE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/drugsdb
    username: root
    password: Fall@4324
    driver-class-name: com.mysql.jdbc.Driver

